apiVersion: apps/v1
kind: Deployment
metadata:
  name: apeks-deployment
  namespace: apeks-demo
  labels:
    app.kubernetes.io/name: apeks
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: apeks
  template:
    metadata:
      labels:
        app.kubernetes.io/name: apeks
    spec:
      containers:
      - name: apeks-container
        image: hub.comcast.net/pps-tie-db/op7app/apeks-image:latest
        command: ["sh", "-c", "echo Hello Kubernetes! && sleep 3600"]
        ports:
          - name: http
            containerPort: 80        
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.1"
            memory: "256Mi"
