apiVersion: v1
kind: Service
metadata:
  name: apeks-service
  namespace: apeks-demo
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: apeks
  ports:
    - protocol: TCP
      port: 80
      targetPort: http